# Generated by Django 5.0.2 on 2024-03-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('conAlcohol', 'Con Alcohol'), ('sinAlcohol', 'Sin Alcohol'), ('cafeteria', 'Cafetería')], max_length=20)),
                ('ocasion', models.CharField(max_length=20)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('preparacion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenRecetaBebida', models.ImageField(blank=True, null=True, upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Dulce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('postre', 'Postre'), ('snack', 'Snack')], max_length=20)),
                ('ocasion', models.CharField(max_length=20)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('preparacion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenRecetaDulce', models.ImageField(blank=True, null=True, upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Salada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('platoPrincipal', 'Plato Principal'), ('entrada', 'Entrada'), ('snack', 'Snack')], max_length=20)),
                ('ocasion', models.CharField(max_length=20)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('preparacion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenRecetaSalada', models.ImageField(blank=True, null=True, upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(null=True)),
                ('fechaPublicacion', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
