# Generated by Django 5.0.2 on 2024-03-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='imagenRecetaBebida',
            field=models.ImageField(blank=True, null=True, upload_to='aplicacion/static/galeria'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='tipo',
            field=models.CharField(choices=[('conAlcohol', 'Con Alcohol'), ('sinAlcohol', 'Sin Alcohol'), ('cafeteria', 'Cafetería')], default='snack', max_length=20),
        ),
        migrations.AlterField(
            model_name='dulce',
            name='imagenRecetaDulce',
            field=models.ImageField(blank=True, null=True, upload_to='aplicacion/static/galeria'),
        ),
        migrations.AlterField(
            model_name='dulce',
            name='tipo',
            field=models.CharField(choices=[('postre', 'Postre'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
        migrations.AlterField(
            model_name='salada',
            name='imagenRecetaSalada',
            field=models.ImageField(blank=True, null=True, upload_to='aplicacion/static/galeria'),
        ),
        migrations.AlterField(
            model_name='salada',
            name='tipo',
            field=models.CharField(choices=[('platoPrincipal', 'Plato Principal'), ('entrada', 'Entrada'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
    ]
