# Generated by Django 5.0.2 on 2024-03-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='imagenRecetaBebida',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='dulce',
            name='imagenRecetaDulce',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='salada',
            name='imagenRecetaSalada',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
    ]
