# Generated by Django 5.0.2 on 2024-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_bebida_usuario_dulce_usuario_salada_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='tipo',
            field=models.CharField(choices=[('Con Alcohol', 'Con Alcohol'), ('Sin Alcohol', 'Sin Alcohol'), ('Cafetería', 'Cafetería')], default='sinAlcohol', max_length=20),
        ),
        migrations.AlterField(
            model_name='dulce',
            name='tipo',
            field=models.CharField(choices=[('Postre', 'Postre'), ('Snack', 'Snack')], default='snack', max_length=20),
        ),
        migrations.AlterField(
            model_name='salada',
            name='tipo',
            field=models.CharField(choices=[('Plato Principal', 'Plato Principal'), ('Entrada', 'Entrada'), ('Snack', 'Snack')], default='snack', max_length=20),
        ),
    ]
