# Generated by Django 5.0.2 on 2024-03-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_bebida_tipo_alter_dulce_tipo_alter_salada_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salada',
            name='usuario',
        ),
    ]
