# Generated by Django 5.0.2 on 2024-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_salada_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salada',
            name='imagenRecetaSalada',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
