# Generated by Django 5.0.2 on 2024-03-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_alter_salada_imagenrecetasalada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulce',
            name='imagenRecetaDulce',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
