# Generated by Django 5.0.2 on 2024-03-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_remove_post_autor_post_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatares/default.jpg', upload_to='avatares'),
        ),
    ]
