# Generated by Django 5.0.2 on 2024-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0022_rename_post_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='media/avatares/default.jpg', upload_to='avatares/'),
        ),
    ]
